### ISSUE TITLE
Project Proposal Response - First Iteration

### ISSUE THREAD

**Issue by IanY11** [CapstoneProjectQPP/QuantumPermutationPad#19]
# Summary
A template for the project proposal response has been added to our Google drive here: [https://docs.google.com/document/d/1xw6nAtqDT5o1Czi-_UobiaCk-ly6YIbf/edit?usp=sharing&ouid=116293067301945525613&rtpof=true&sd=true](https://docs.google.com/document/d/1xw6nAtqDT5o1Czi-_UobiaCk-ly6YIbf/edit?usp=sharing&ouid=116293067301945525613&rtpof=true&sd=true)

We are supposed to complete at least 2 iterations of the proposal before it is due on January 23rd.

Before we can complete the first iteration, we need to meet with our client (Professor Knudsen), and ask clarifying questions about the Project Proposal. #21 

# Sections
* [x] Objective - Ahmed
* [x] Introduction - Danh
* [x] Proposed Solution - Ahmed
* [x] Project Overview Statement - Ian & Wentao

**Comment by Iyury1** [comment]
Each team member will complete their assigned section by Sunday 2023-01-15.
