### ISSUE TITLE
Project Proposal Response - Second Iteration

### ISSUE THREAD

**Issue by IanY11** [CapstoneProjectQPP/QuantumPermutationPad#23]
# Summary
A template for the project proposal response has been added to our Google drive here: [https://docs.google.com/document/d/1xw6nAtqDT5o1Czi-_UobiaCk-ly6YIbf/edit?usp=sharing&ouid=116293067301945525613&rtpof=true&sd=true](https://docs.google.com/document/d/1xw6nAtqDT5o1Czi-_UobiaCk-ly6YIbf/edit?usp=sharing&ouid=116293067301945525613&rtpof=true&sd=true)

We are supposed to complete at least 2 iterations of the proposal before it is due on January 23rd.

Before we can complete the second iteration, we must complete the first iteration. #19 

# Sections
* [x] Objective
* [x] Introduction
* [x] Proposed Solution
* [x] Project Overview Statement

**Comment by Iyury1** [comment]
Revise POS objectives to be more general and address professor's comment

Add obvious risks to POS.

Communicate minimum functionality in Proposed Solution
